apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
# Annotation to add an interface (using multus) on the user_net
# and NGINX is reachable at the IP:80 on the user_net
#      annotations:
#        k8s.v1.cni.cncf.io/networks: default/vcdn-user
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.repository }}:1.14.2
        ports:
        - containerPort: 80
